# Generated by Django 4.0.2 on 2022-04-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('OF', 'Offline'), ('ON', 'Online'), ('BU', 'Busy')], default='ON', max_length=2),
        ),
    ]
