# Generated by Django 4.0.2 on 2022-04-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_patient_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
    ]
