# Generated by Django 4.0.2 on 2022-03-16 22:24

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.UUIDField(default=shortuuid.main.ShortUUID.uuid, editable=False)),
                ('booking_status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected'), ('CA', 'Canceled'), ('CO', 'Completed')], default='PE', max_length=2)),
                ('payment_status', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('booking_slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.appointmentslot')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient')),
            ],
        ),
    ]
