# Generated by Django 4.0.2 on 2022-03-23 12:56

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.UUIDField(default=shortuuid.main.ShortUUID.uuid, editable=False),
        ),
    ]
