# Generated by Django 4.0.2 on 2022-04-09 16:51

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.UUIDField(default=shortuuid.main.ShortUUID.uuid, editable=False),
        ),
    ]
