# Generated by Django 4.0.2 on 2022-04-09 16:57

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bookings', '0005_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.UUIDField(default=shortuuid.main.ShortUUID.uuid, editable=False),
        ),
    ]
