# Generated by Django 4.0.2 on 2022-04-26 04:35

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_sid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=255),
        ),
    ]
