# Generated by Django 4.0.2 on 2022-04-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_doctor_specialty'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorditem',
            name='medical_record',
        ),
        migrations.AddField(
            model_name='recorditem',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
